name: 'HA-Chrome-VNC'
version: '1.0.0'
slug: 'ha_chrome_vnc'
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - arm64
  - i386
startup: services
codenotary: info@lklaus.ch
description: Chrome Browser accesible with VNC on Port 5900/TCP
#image: 'lela810/ha-chrome-vnc-addon'
ports:
  5900/tcp: 5900
ports_description:
  5900/tcp: VNC Port (required)
#options:
#CONFIG_LOCATION: '/config/addons_config/ha-chrome-vnc'
map:
  - config:rw
