name: 'HA-Chrome-VNC'
version: '1.0.11'
slug: 'ha_chrome_vnc'
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
codenotary: info@lklaus.ch
video: true
full_access: true
kernel_modules: true
apparmor: true
privileged:
  - SYS_MODULE
  - SYS_ADMIN
  - NET_ADMIN
environment:
  - TZ=Europe/Zurich
  - PGID=1000
  - PUID=1000
devices:
  - /dev/dri:/dev/dri
image: registry.hub.docker.com/lela810/ha-chrome-vnc-addon
webui: http://[HOST]:[PORT:6080]/vnc.html?resize=downscale&autoconnect=1&password=31Yxcvbnm
description: Firefox Browser accesible with VNC on Port 5900/TCP or NoVNC on Port 6080/TCP
ports:
  5900/udp: 5900
  5900/tcp: 5900
  3000/tcp: 3000
#options:
#CONFIG_LOCATION: '/config/addons_config/ha-chrome-vnc'
map:
  - config:rw
