name: 'HA-Chrome-VNC'
version: '1.0.2'
slug: 'ha_chrome_vnc'
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
codenotary: info@lklaus.ch
image: registry.hub.docker.com/lela810/ha-chrome-vnc-addon:latest
description: Firefox Browser accesible with VNC on Port 5900/TCP or NoVNC on Port 6080/TCP
#image: 'lela810/ha-chrome-vnc-addon'
ports:
  5900/tcp: 5900
  6080/tcp: 6080
ports_description:
  5900/tcp: VNC Port (required)
  6080/tcp: NoVNC Port (optional)
#options:
#CONFIG_LOCATION: '/config/addons_config/ha-chrome-vnc'
map:
  - config:rw
