name: 'HA-Chrome-VNC'
version: '1.1.2'
slug: 'ha_chrome_vnc'
panel_icon: 'mdi:firefox'
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
codenotary: info@lklaus.ch
apparmor: false
ingress: true
ingress_port: 5800
ports:
  5900/tcp: 5900
  5800/tcp: 5800
ports_description:
  5900/tcp: VNC Port (required)
  5800/tcp: Web Port (optional)
image: registry.hub.docker.com/lela810/ha-chrome-vnc-addon
description: Firefox Browser accesible with VNC on Port 5900 or Web on Port 5800
map:
  - share:rw
