name: 'HA-Chrome-VNC'
version: '1.0.17'
slug: 'ha_chrome_vnc'
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
codenotary: info@lklaus.ch
video: true
image: registry.hub.docker.com/lela810/ha-chrome-vnc-addon
webui: https://[HOST]:[PORT:11443]
description: Firefox Browser accesible with VNC on Port 5900/TCP or NoVNC on Port 6080/TCP
ports:
  5900/udp: 5900
  5900/tcp: 5900
  80/tcp: 1180
  443/tcp: 11443
#options:
#CONFIG_LOCATION: '/config/addons_config/ha-chrome-vnc'
map:
  - config:rw
