name: 'HA-Chrome-VNC'
version: '1.0.25'
slug: 'ha_chrome_vnc'
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
codenotary: info@lklaus.ch
ingress: true
ingress_port: 5900
image: registry.hub.docker.com/lela810/ha-chrome-vnc-addon
webui: https://[HOST]:[PORT:11443]
description: Firefox Browser accesible with VNC on Port 5900 or NoVNC on Port 1180
#options:
#CONFIG_LOCATION: '/config/addons_config/ha-chrome-vnc'
map:
  - config:rw
