name: 'HA-Chrome-VNC'
version: '1.0.27'
slug: 'ha_chrome_vnc'
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
codenotary: info@lklaus.ch
apparmor: false
ports:
  5900/tcp: 5900
  5800/tcp: 5800
ports_description:
  5900/tcp: VNC Port (required)
  5800/tcp: Web Port (optional)
image: registry.hub.docker.com/lela810/ha-chrome-vnc-addon
webui: https://[HOST]:[PORT:5800]
description: Firefox Browser accesible with VNC on Port 5900 or NoVNC on Port 1180
map:
  - share:rw
